# Generated by Django 3.2.20 on 2023-07-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcategory_name', models.CharField(max_length=255)),
                ('category_image', models.FileField(upload_to='category_image')),
                ('diat', models.BooleanField(default=True)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=255)),
                ('food_description', models.CharField(max_length=1000)),
                ('food_image', models.FileField(upload_to='food_image')),
                ('food_price', models.FloatField()),
                ('food_availablity', models.BooleanField(default=False)),
                ('food_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Base.foodcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('nubmber_of_seats', models.IntegerField()),
                ('table_location', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=255)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.foodmenu')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.tables')),
            ],
        ),
        migrations.CreateModel(
            name='BillOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(max_length=255, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=1000, null=True)),
                ('foodmenu', models.ManyToManyField(to='Base.FoodMenu')),
            ],
        ),
    ]
